### ISSUE TITLE
google login crash onActivitiyResult

### ISSUE THREAD

**Issue by dogeri28** [WindSekirun/RxSocialLogin#1]
It seems the google authentication, doesnt seem to work. Please is there anything that i might be doing wrong. i have also enabled the option on firebase and produced a debugged version of the SHA1 hash key. i also downloaded the google services json in my project. Please what can i be doing wrong that it calls back with Google sign in failed

**Comment by WindSekirun** [comment]
Can you follow up with this step?

1. Configure API Project in [here](https://developers.google.com/identity/sign-in/android/start-integrating)
2. In AS 3.1, enter 'Firebase' and click 'Authentication' and click 'Connect to Firebase' and 'Add Firebase Authentication to your app'
 -  in this step, you will save your 'google-services.json' in your app module directory.
3. Enable Google as authentication provider in Firebase Console
4. Find 'Web Client ID' in Firebase console. you can find this information in sub-section of authentication provider.
5. Provide your 'Web Client ID' into GoogleConfig.setClientTokenId()

if you still failed, notice to me. i'll post some post about setting step with some picture.

**Comment by WindSekirun** [comment]
I posted some tutorial on my personal blog, you can see [this link](https://blog.uzuki.live/implement-google-login-with-rxsociallogin-english/) for tutorial. 

and you don't need to configure API Project. There is all steps of Google Login.

1. In AS 3.1, enter 'Firebase' and click 'Authentication' and click 'Connect to Firebase' and 'Add Firebase Authentication to your app'. in this step, you will save your 'google-services.json' in your app module directory.
2. Enable Google as authentication provider in Firebase Console
3. Find 'Web Client ID' in Firebase console. you can find this information in sub-section of authentication provider.
4. Provide your 'Web Client ID' into GoogleConfig.setClientTokenId()

**Comment by dogeri28** [comment]
Thank you very much, it worked. i followed the steps on your blog. However for clarity can you update the github step instead of google and change the .setClientTokenId("<YOUR-API-KEY>") to  .setClientTokenId("<**YOUR-WEB-CLIENT-ID**>")   in the google section. Apart from that thank you if you had a donate button i would have donated something, maybe its worth having on your github page. I will be moving onto using the twitter option shortly.
