### ISSUE TITLE
Twitter Profile Image 

### ISSUE THREAD

**Issue by dogeri28** [WindSekirun/RxSocialLogin#15]
Please include this functionality, that we can get the profile image url of the twitter account.

**Comment by WindSekirun** [comment]
i implemented '/1.1/account/verify_credentials.json' api in TwitterLogin Since 1.0.0 which will be officially released in a few days.

According to this api, we can add email, profilePicture, nickname information into LoginResultItem()

**Comment by WindSekirun** [comment]
Hey, finally i released 1.0.0 officially today! so we can get 'Twitter profile image' in Rx-way. check out new README, and apply feature and feedback to me. there are some changes of naming of class, so be careful to migrate to 1.0.0. thanks.
