### ISSUE TITLE
Fails to build when Proguard is enabled

### ISSUE THREAD

**Issue by dogeri28** [WindSekirun/RxSocialLogin#2]
Hello,

Please can you verify that your library can be built with Proguard enabled, as when i comment the library my project builds fine with proguard, but when i then include the rxsocial login it doesnt.

Regards
Sunny

**Comment by WindSekirun** [comment]
I updated proguard rules for sample application in [here](https://github.com/WindSekirun/RxSocialLogin/blob/master/demo/proguard-rules.pro), but i can't check line and google login, so notify to me when build is failed.

**Comment by dogeri28** [comment]
Hi, 
    The proguard rules seems to work, thanks a lot. sorry to get back late. Regards
