### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by WindSekirun** [WindSekirun/RxSocialLogin#33]

**Comment by WindSekirun** [comment]
Internally, I used RxSocialLogin works fine with AndroidX-migrated projects. so this can't be problem.

**Comment by mittalharsh2810** [comment]
With Android X its not working.

**Comment by WindSekirun** [comment]
In my project, androidx project is working well. I'll publish androidx version in tommorow.

**Comment by mittalharsh2810** [comment]
I got this error:

`Error inflating class [com.google.android.material.textfield.TextInputLayout`
After implementing rxSocial

**Comment by WindSekirun** [comment]
Can you wait 20 minutes? I'm going to migrate the androidx to the snapshot build.

**Comment by mittalharsh2810** [comment]
AndroidX with material library:
`com.google.android.material:material`

**Comment by WindSekirun** [comment]
Release as '1.2.0-androidx'.
```
implementation 'com.github.WindSekirun:RxSocialLogin:1.2.0-androidx'
```
I check build success when adding ```com.google.android.material:material:1.0.0-beta01```. 
If it still does not build, please let me know. (It's late at night in my time zone(UTC+9), so it may take some time to answer.)

**Comment by WindSekirun** [comment]
Close cause inactivity
