### ISSUE TITLE
Not getting result after login

### ISSUE THREAD

**Issue by dkk009** [WindSekirun/RxSocialLogin#34]
For facebook login not getting result
     RxSocialLogin.result(this).subscribe({
            Timber.d { "FirstName: ${it.firstName}" }
        },
                { Timber.e(it.cause)})
After onActivityResult.

**Comment by WindSekirun** [comment]
I find some missing point in README.
you should do 'RxSocialLogin.initialize(this)' before 'RxSocialLogin.result(this)`
It will be fine.

I updated some sample related of your issue. please run the sample app and let us know if the problem recurs. (I tested it on my own device, but it seems to work.)

**Comment by WindSekirun** [comment]
One more thing, if you doesn't enable 'behaviorOnCancel' on Config in Application, please enable on. somethimes facebook return onCancel() in their callback.

If none of the situations seem appropriate, please provide code to reproduce the issue.

**Comment by dkk009** [comment]
Issue is fixed

**Comment by WindSekirun** [comment]
thanks for fast response, i'll update readme as soon as possible.
