### ISSUE TITLE
Not getting Facebook access token from success result

### ISSUE THREAD

**Issue by dkk009** [WindSekirun/RxSocialLogin#36]
Not getting facebook access token after success full login, apart access token every thing is coming properly.

FirstName: *****
FacebookId:22**********
FacebookAccessToken:

**Comment by WindSekirun** [comment]
This is not a bug. You can get AvcessToken by AccessToken.getCurrentAccessToken() statement.

**Comment by WindSekirun** [comment]
Start from v 1.2.0, you can get accessToken of Facebook with LoginResultItem.accessToken.
