### ISSUE TITLE
ERROR: Failed to resolve: com.kakao.sdk:usermgmt:1.11.1

### ISSUE THREAD

**Issue by mittalharsh2810** [WindSekirun/RxSocialLogin#46]
I am getting the error on this with AndroidX Gradle
Please try to solve this.

**Comment by WindSekirun** [comment]
Please attach erroe log and your build gradle file without any privacy information.

**Comment by WindSekirun** [comment]
Can you check your repositories has this repository?

maven { url 'http://devrepo.kakao.com:8088/nexus/content/groups/public/' }

**Comment by WindSekirun** [comment]
Has the issue been resolved?

**Comment by mittalharsh2810** [comment]
Yes, It is solved by adding that line.
Thanks @WindSekirun

**Comment by mittalharsh2810** [comment]
Yes, It is solved by adding that line.
Thanks @WindSekirun
