### ISSUE TITLE
Duplicate class com.android.vending.billing.IInAppBillingService found in modules ?

### ISSUE THREAD

**Issue by raykang49** [WindSekirun/RxSocialLogin#54]
안녕하세요. 노고가 많으십니다.
Duplicate class com.android.vending.billing.IInAppBillingService found in modules jetified-RichUtilsKt-2.3.1-runtime.jar (com.github.WindSekirun:RichUtilsKt:2.3.1) and jetified-library-1.0.44.jar (com.anjlab.android.iab.v3:library:1.0.44) 
이거 어떻게 해결하는지 몰겠는데... 좀 도와주시면 안되나요?
com.anjlab.android.iab.v3:library:1.0.44 이걸로 인앱결제 추가 해놨는데 
두개 동시에 못쓰는건가요?
소셜로긴인데 왜 IInAppBillingService 부분이 문제가 될까요?
초보라 잘부탁듸립니다.

**Comment by WindSekirun** [comment]
@raykang49 
안녕하세요 (_ _)
내부적으로 RxSocialLogin에 RichUtilsKt에 대한 의존성이 있고, 해당 라이브러리에는 인앱용 도구가 포함되어 있습니다. 
현재 해당 문제를 해결한 1.3.2 버전을 배포중에 있사오니, 해당 버전으로 사용하시면 문제가 해결될 것으로 보입니다. 배포되면 댓글로 알려드리겠습니다.

**Comment by WindSekirun** [comment]
@raykang49 또한, 현재 사용중이신 버전이 `1.2.1-androidx` 맞으신가요? 당시와 달리 androidx가 많이 배포되었으므로, androidx 버전 사용을 권장드립니다. (현재 배포중인 버전도 `1.2.5-androidx` 입니다.)

**Comment by WindSekirun** [comment]
@raykang49 
`1.2.5.1`
`1.2.5-androidx`

배포 완료되었습니다. 사용까지 10분 가량 소요될 수 있습니다.

**Comment by raykang49** [comment]
넴 1.2.1-androidx 입니다. 총알서비스 감사드립니다 ^_^)/

**Comment by raykang49** [comment]
송구하지만 ㅠㅠ 

Duplicate class com.android.vending.billing.IInAppBillingService found in modules jetified-RichUtilsKt-2.4.0-remove-inapp-runtime.jar (com.github.WindSekirun:RichUtilsKt:2.4.0-remove-inapp) and jetified-billing-2.0.1-runtime.jar (com.android.billingclient:billing:2.0.1)
Duplicate class com.android.vending.billing.IInAppBillingService$Stub found in modules jetified-RichUtilsKt-2.4.0-remove-inapp-runtime.jar (com.github.WindSekirun:RichUtilsKt:2.4.0-remove-inapp) and jetified-billing-2.0.1-runtime.jar (com.android.billingclient:billing:2.0.1)
Duplicate class com.android.vending.billing.IInAppBillingService$Stub$Proxy found in modules jetified-RichUtilsKt-2.4.0-remove-inapp-runtime.jar (com.github.WindSekirun:RichUtilsKt:2.4.0-remove-inapp) and jetified-billing-2.0.1-runtime.jar (com.android.billingclient:billing:2.0.1)

몇번을 해봐도 안되서요 RichUtilsKt-2.4.0-remove-inapp-runtime.jar 에서 
왜 IInAppBillingService found  인지 혹시 파일명 자체 해결이 능력이 안되서 
그런데 딱 한번만 더 봐주시면 안될까요?

jetified-RichUtilsKt-2.3.1-runtime.jar 
jetified-RichUtilsKt-2.4.0-remove-inapp-runtime.jar

**Comment by WindSekirun** [comment]
포함이 되어있지 않은 것으로 확인됩니다.
https://github.com/WindSekirun/RichUtilsKt/tree/2.4.0-remove-inapp/RichUtils/src/main


gradlew clean을 해보시는걸 추천드립니다

2019년 12월 30일 (월) 오전 12:32, RayKang <notifications@github.com>님이 작성:

**Comment by raykang49** [comment]
https://jitpack.io/com/github/WindSekirun/RichUtilsKt/2.4.0-remove-inapp/build.log

>> 예전에 RichUtilsKt/2.4.0-remove-inapp 빌드하실때 아래 로그를 보아 RInAppBilling.kt가 포함된거같은데... 확인좀해주세요.
w: /home/jitpack/build/RichUtils/src/main/java/pyxis/uzuki/live/richutilskt/module/iap/RInAppBilling.kt: (168, 17): Variable 'sku' is never used

**Comment by raykang49** [comment]
https://github.com/WindSekirun/RichUtilsKt/tree/2.4.0-remove-inapp/RichUtils/src/main
에 "RInAppBilling.kt" 삭제 되어있습니다.

하지만, 
implementation 'com.github.WindSekirun:RichUtilsKt:2.4.0-remove-inapp' 

![Screen Shot 2019-12-30 at 12 29 17 PM](https://user-images.githubusercontent.com/37016532/71573475-6b2c3680-2b27-11ea-965d-79cac0708cf8.png)

https://jitpack.io/com/github/WindSekirun/RichUtilsKt/2.4.0-remove-inapp/build.log

![Screen Shot 2019-12-30 at 5 14 12 PM](https://user-images.githubusercontent.com/37016532/71573563-dd048000-2b27-11ea-8007-624712f50d8f.png)

gradle 에서 불러오는것이 현재 git에서 가져오는것 같지 않고 jitpack 배포 파일로 배포되는거 같습니다.

재배포 또는 확인 부탁드립니다.

**Comment by WindSekirun** [comment]
@raykang49 확인 결과, inapp 파일이 제대로 제거되지 않은 버전으로 배포가 된 것으로 보입니다.
`1.2.5.3-androidx` 및 `1.2.5.3` 으로 배포중이며 사용하기까지 10분 이상 걸릴 수 있습니다.

배포되고 해당 현상이 해결되면 Close 부탁드립니다.
