### ISSUE TITLE
The file ‘RInAppBilling.kt’ was not removed in RichUtilsKt:2.4.0-remove-inapp

### ISSUE THREAD

**Issue by raykang49** [WindSekirun/RxSocialLogin#55]
안녕하세요. 

https://github.com/WindSekirun/RichUtilsKt/tree/2.4.0-remove-inapp/RichUtils/src/main/java/pyxis/uzuki/live/richutilskt/module   여기에는  RInAppBilling.kt파일이 없는데

Gradle 에서 내려받은 RichUtilsKt-2.4.0-remove-inapp-sources.jar 여차여차 찾아내서 열어보면 여전히 들어있습니다.

![Screen Shot 2019-12-30 at 12 16 18 PM](https://user-images.githubusercontent.com/37016532/71566846-4c657a00-2afe-11ea-89d8-a5879a5f8cbc.png)

![Screen Shot 2019-12-30 at 12 29 17 PM](https://user-images.githubusercontent.com/37016532/71567109-06a9b100-2b00-11ea-985d-2fdf6e318c93.png)

**Comment by WindSekirun** [comment]
#54 에서 통합 관리하겠습니다.
