### ISSUE TITLE
I can't run demo app, There's no google-services.json file here.

### ISSUE THREAD

**Issue by greedy0110** [WindSekirun/RxSocialLogin#61]
My demo build is failed with error message like this. 

```
Execution failed for task ':demo:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/sinseungmin/AndroidProject/RxSocialLogin/demo/src/debug/google-services.json
  /Users/sinseungmin/AndroidProject/RxSocialLogin/demo/google-services.json
```

How can I play demo? 
Do I have to put on my own `google-service.json` there? Or Is it just kind of bug?

**Comment by WindSekirun** [comment]
Somehow, few of services notice me 'your secret is leaked' error (and so many email), so currently sample application doesn't provide own google-services.json.

you can use sample app with this approach
1. Make sample application
2. Register to Firebase and getting google-services.json
3. change package name with sample application's package name in google-services.json

This will make build is success, but GoogleLogin isn't working
